debug: false

#auctuator? ?? endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fcboard.projectboard: debug
    org.springframework.servlet : debug #req, res log
    org.hibernate.type.descriptor.sql.BasicBinder : trace #jpa ?? ?? ??(??? ???? ?? ??)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: crumbled
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #???? ?? ??? ??(resource/data.sql)
    hibernate.ddl-auto: create
    show-sql: true
    properties: #?? ???? ???? ????? ??? ? ?? ??
      hibernate.format_sql: true #?? ??? ?? ??? ??
      hibernate.default_batch_fetch_size: 100 #??? 100??
    h2.console.enabled: true
    sql.init.mode: always #data.sql? ?? ????

---
##테스트 디비용 프로필
#spring:
#  config:
#    activate:
#      on-profile: testdb
#  #h2 호환성 이용(mysql 버전으로)
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init :
#      mode: always
#  test.database.replace: none #jpa테스트에서 테스트용db 사용하지 않고 내가 설정한 디비로 테스트.(전역설정, 개별테스트에서 따로 설정도 가능)