debug: false

#auctuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fcboard.projectboard: debug
    org.springframework.servlet : debug #req, res log
    org.hibernate.type.descriptor.sql.BasicBinder : trace #jpa 쿼리 파라미터

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: crumbled
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false
  sql.init.mode: always #data.sql
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
